export const SETTINGS_SECTION_LABELS = [
  { name: 'order', labelKey: 'modals.main.marketplace.product.overview' },
  { name: 'navbar', labelKey: 'modals.main.settings.sections.appearance.navbar.title' },
  { name: 'greeting', labelKey: 'modals.main.settings.sections.greeting.title' },
  { name: 'time', labelKey: 'modals.main.settings.sections.time.title' },
  { name: 'quicklinks', labelKey: 'modals.main.settings.sections.quicklinks.title' },
  { name: 'quote', labelKey: 'modals.main.settings.sections.quote.title' },
  { name: 'date', labelKey: 'modals.main.settings.sections.date.title' },
  { name: 'message', labelKey: 'modals.main.settings.sections.message.title' },
  { name: 'background', labelKey: 'modals.main.settings.sections.background.title' },
  { name: 'search', labelKey: 'modals.main.settings.sections.search.title' },
  { name: 'weather', labelKey: 'modals.main.settings.sections.weather.title' },
  { name: 'appearance', labelKey: 'modals.main.settings.sections.appearance.title' },
  { name: 'language', labelKey: 'modals.main.settings.sections.language.title' },
  { name: 'advanced', labelKey: 'modals.main.settings.sections.advanced.title' },
  { name: 'stats', labelKey: 'modals.main.settings.sections.stats.title' },
  { name: 'experimental', labelKey: 'modals.main.settings.sections.experimental.title' },
  { name: 'changelog', labelKey: 'modals.main.settings.sections.changelog.title' },
  { name: 'about', labelKey: 'modals.main.settings.sections.about.title' },
];
